[phases.setup]
# Įdiek Python
nixPkgs = ["python311", "pipx"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

[start]
# Tavo projektas vadinasi 'barjob' -> WSGI = barjob.wsgi
cmd = "gunicorn barjob.wsgi:application --bind 0.0.0.0:$PORT"
