# Generated by Django 5.1.4 on 2025-01-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipeimage_delete_category_remove_recipe_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
