# Generated by Django 5.1.4 on 2025-01-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
