# Generated by Django 5.1.4 on 2025-01-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_code_alter_recipe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/images/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/images/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/images/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/images/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/images/'),
        ),
    ]
